services:
  postgres:
    container_name: postgresql
    image: postgres:13
    environment:
      - POSTGRES_DB=web3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=061200
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    command: sh -c "node ace migration:run --force && node bin/server.js"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.production
    ports:
      - "5173:8080"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  postgres-data:
